agateblue/django-dynamic-preferences

dynamic_preferences/forms.py

In relation to #44, I think there's just one more change necessary to propagate the order through to the form :smile:
(Sorry if I got something wrong with the software architecture.)

Propagate order of preferences through to forms

---

dynamic_preferences/serializers.py

Just a minor edit, I stumbled across this the other day (I was writing a data migration to "migrate" an preference definition change, but that's mostly unrelated). I actually haven't had any problems with it because (at least for me) it always serializes to "True" and "False", which are valid items in the list as-is, so it works fine. But I assume there were meant to be commas on each line?
(duplicate of #54, this time to the develop branch)

Add missing commas to BooleanSerializer.true/false

---

HISTORY.rst
dynamic_preferences/registries.py
dynamic_preferences/templates/dynamic_preferences/base.html
dynamic_preferences/templates/dynamic_preferences/form.html
dynamic_preferences/templates/dynamic_preferences/sections.html
dynamic_preferences/users/registries.py
dynamic_preferences/views.py
tests/settings.py
tests/test_global_preferences.py
tests/urls.py

@JanMalte and @leetucker this should fix your issues, can you test this in your projects and tell me if everything is okay?
Basically, the template context for the form template now includes:
1. The preference registry, which you can use to retrieve sections by looping on the `section_objects` attribute: `{% for section in registry.section_objects %}{{ section.verbose_name }}{% endfor %}
2. The current section object (if any) is accessible under the `section` context key. If no section is selected, this value will be at `None`: `Current section is {{ section.verbose_name }}`
Hopefully, this should make it easier to write templates that involves sections and i18n.

Fixed #49 and fixed #71 by passing section objects in templates, and not only the sections identifiers

---

docs/conf.py
docs/index.rst
docs/preference_types.rst
dynamic_preferences/managers.py
dynamic_preferences/serializers.py
dynamic_preferences/settings.py
dynamic_preferences/types.py
tests/settings.py
tests/test_app/dynamic_preferences_registry.py
tests/test_global_preferences.py
tests/test_types.py

This is based on the work by @macolo in #37 to implement a File preference type, with various changes though, as the original PR was submitted 18 months ago.
It includes:
We still need the following though:
@fabrixxm you can start review and test it if you want, although I suspect forms won't work out of the box in the current state (that would be a good surprise if they did).

Rework on #37 by @macolo to implement File preference

---

dynamic_preferences/managers.py
tests/test_manager.py

this is a critical issue, because due to a logical error in `manager.create_db_pref`, preferences values where systematically restored to their default value.

Fix a data loss issue where preferences values are reset to default

---

dynamic_preferences/managers.py

The symptom I'm getting is the following: When `Manager.by_name()` is called repeatedly, it hits the database with a query per preference for most preferences (I have about 100 of them) on every page load. On further inspection, it seems the cache finds only those preferences that have previously been referenced directly, as opposed to via `by_name()` (and hence via `all()`).
For context, we have a context processor that provides access to the preferences associated with a particular model (called `Tournament`), that you can see in [this file here](https://github.com/czlee/tabbycat/blob/51b5faf9e117ac6460bb89d155dd4c9ac0a5355a/tabbycat/utils/context_processors.py#L18). It's similar to the context processor in the library for global preferences, just for a particular model instance.
I …

Cache values when queried in all()

---

dynamic_preferences/managers.py

As discussed in #91.
It took me a few iterations to notice that I was basically duplicating `load_from_db()` (as you can see from the commit history), so the current version just calls `load_from_db()`. I suspect filtering the queryset for just those fields missing from the cache would add more complexity than it's worth, so I ended up getting it to retrieve everything unless _everything_ was found in the cache.
Then, since you already have all the data, you may as well use it, so in line 203 it just overwrites the value retrieved from cache. In practice, unless the cache has entries that the database doesn't, line 203 is probably the same as `return self.load_from_db()`.
I sort of wondered whether it should include fallback preferences in the returned dict, and initially got it to do so, …

Retrieve existing preferences in bulk

---

dynamic_preferences/management/commands/checkpreferences.py

This method is more of a throwback to how it used to work than what is discussed in #75. I was thinking that creating the fallback would still litter the logs with fallback warning messages, which for a command that whose point is to delete them, would probably be more annoying than helpful.

Fixed #75: Fix checkpreferences command

---

.gitignore
dynamic_preferences/api/serializers.py
tests/test_app/dynamic_preferences_registry.py
tests/test_global_preferences.py
tests/test_rest_framework.py

Also get test from #98 to ensure the issue won't happen again.

Fixed #97 (and potentially other issues), missing to_python() call in REST serializer

---

dynamic_preferences/serializers.py
dynamic_preferences/types.py
tests/test_app/dynamic_preferences_registry.py
tests/test_global_preferences.py
tests/test_serializers.py
tests/test_types.py

For #8 
@EliotBerriot I just finished adding `DateTimePreference`. Some things to note,
1. I'm serializing to isoformat
2. I've handled the case when `settings.USE_TZ=false` in which case we'll serialise without a timezone info.
3. I've also tested that if user sets `settings.TIME_ZONE` to a valid timezone name then the I serialise to that timezone.
Let me know how this looks :)

Add datetime preference type

---

dynamic_preferences/serializers.py
tests/test_app/dynamic_preferences_registry.py
tests/test_global_preferences.py
tests/test_types.py

fixes #111 by ensuring that if the file saving process modified the path
name, the modifications are saved back to the preference, rather than using the
original file path.

use path as returned by storage save method

---

dynamic_preferences/types.py
tests/test_rest_framework.py

@EliotBerriot I just noticed a bug in duration preference serializer when using rest framework. When using the `GlobalPreferenceSerializer` I expected the duration to be serialized to something like `03:00:00` but instead it just returns a string representation of the timedelta like `datetime.timedelta(0, 10800)`
I've modified a test case to illustrate the point. I'll fix this soon.

Duration preference serialization issue in rest framework

---

HISTORY.rst
dynamic_preferences/api/viewsets.py

Fix #127: removed typo in API code that could cause a crash

Fix #127: removed typo in API code that could cause a crash

---

dynamic_preferences/migrations/0001_initial.py
dynamic_preferences/migrations/0002_auto_20150712_0332.py

In Django 2.0 the on_delete field is required for ForeignKey fields 
https://docs.djangoproject.com/en/2.0/ref/models/fields/

Added on_dete=models.CASCADE to migrations for Django 2.0 compatibility

---

dynamic_preferences/admin.py

Hi again! Two hopefully small changes:
1. I added `instance` to the admin form fields for per-instance preferences. I assume this is what you intended, since `instance` was already in `raw_id_fields`. I haven't put it in `readonly_fields`, though.
2. Currently if you enable the `ADMIN_ENABLE_CHANGELIST_FORM` option, per-instance preference pages crash with an `AttributeError` because `PerInstancePreferenceAdmin.changelist_form` isn't defined. So I added this and made it the same as `PerInstancePreferenceAdmin.form`, following the example of the other admin classes.
Thanks again for everything 🙂

Add field and changelist_form to PerInstancePreferenceAdmin

---

dynamic_preferences/registries.py

Bugfix for #134.
If `preference` is proxy model (e.g. when you want to have your own admin instead native one), `PreferenceModelsRegistry.register()` sets `self[preference_model]` for proxy model, but `PreferenceModelsRegistry.get_by_preference()` tries to get preference by native model.

Get proper PreferenceModelsRegistry when preference is proxy model

---

dynamic_preferences/exceptions.py
dynamic_preferences/types.py
tests/test_app/dynamic_preferences_registry.py
tests/test_preferences.py

Fix ModelChoicePreference when model is set instead of queryset.
Also, I add the MissingModel exception when model and queryset attributes are unset.

 Fix ModelChoicePreference when using with model attribute and not queryset

---

docs/quickstart.rst
dynamic_preferences/types.py
example/example/dynamic_preferences_registry.py

Handle 'required' attribute for all BasePreferenceType subclass in addition to field_kwargs way.
For example :
class MyPreference(StringPreference):
field_kwargs = {
'required': False
}
equals to :
class MyPreference(StringPreference):
required = False

Handle 'required' attribute for all inherited BasePreferenceType class

---

dynamic_preferences/registries.py

Nothing major, just that it currently throws "tuple index out of range" here rather than raising the actual error, so this change fixes the error message.

Fix string format arguments in get_by_name error

---

dynamic_preferences/types.py

Use `ChoicePreference.get('choice')` instead of direct access to property in order to be able to use a `get_choices() `method.

Fixed direct access to ChoicePreference.choice

---

dynamic_preferences/__init__.py
dynamic_preferences/api/viewsets.py

The `@list_routes` deprecated decorator was removed, using the `@action` instead.

Added djangorestframework 3.10.x compatibility

---

dynamic_preferences/migrations/0003_auto_20151223_1407.py

Every time I run `migrate` when deploying I get
>   Your models have changes that are not yet reflected in a migration, and so won't be applied.
>  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
This is due to the `verbose_name` that was added to `BasePreferenceModel.section` field without running `makemigrations`.
We can obviously create a new migration, but in such cases, a change of `verbose_name` or `help_text`, I prefer editing the last migration of the affected field.

fix(migrations): add missing `verbose_name`

---

dynamic_preferences/serializers.py
dynamic_preferences/types.py
tests/test_app/dynamic_preferences_registry.py
tests/test_global_preferences.py
tests/test_serializers.py
tests/test_types.py

Closes #186 
As I said on #186, recently I've needed a Time preference and created a time preference type in my project.
I wanted to make a PR to add it to this project, because these changes did worked on my django project, but I couldn't properly install the dev environment and run the tests locally, even following the contributing guide. I faced many issues with python versions, since I'm new to python, and I couldn't solve them.
I've follow what @rvignesh89 did on #100. I hope this PR contribute with the project and let me know if I can improve anything.
Thanks.

Add time preference type

---

dynamic_preferences/preferences.py

https://github.com/EliotBerriot/django-dynamic-preferences/issues/163

Fix crash: 'NoneType' object has no attribute 'name'

---

dynamic_preferences/types.py

There is a small typo in dynamic_preferences/types.py.
Should read `timedelta` rather than `timdelta`.

docs: Fix simple typo, timdelta -> timedelta

---

dynamic_preferences/forms.py

Using `PreferencesManager` instead of manual saving the preference instance has the advantage that it triggers the `preference_updated` signal.

Use PreferencesManager for saving preferences in forms

---

dynamic_preferences/forms.py

In `preference_form_builder` there was passed an keyword argument called `model`, if set, to the registry's method `manager`. In the method the provided kwargs are passed directly to `PreferencesManager`, but there is already an argument `model` provided directly:
```
return PreferencesManager(registry=self, model=self.preference_model, **kwargs)
```
The only sensible argument that can passed is `instance`.

Pass instance provided in form builder to manager

---

HISTORY.rst
dynamic_preferences/serializers.py
dynamic_preferences/types.py
example/example/dynamic_preferences_registry.py
tests/test_app/dynamic_preferences_registry.py
tests/test_serializers.py
tests/test_types.py
tests/test_user_preferences.py

This implements a `MultipleChoicePreference`, along the lines of the MultipleChoiceField in Django.
It is based on the previous work in #165 and updates it to current develop branch, adds some fixes (including support for choices containing the separator), and tests.

Add MultipleChoicePreference

---

AUTHORS.rst
dynamic_preferences/serializers.py
tests/test_serializers.py

If you delete an object whose model is also used for a model multiple choice preference, it will cause some trouble because the preference uses `create_deletion_handler` to create a handler for the delete signal of this model. For a normal model choice field that works perfectly, but not for a model multiple choice field: The serializer only supports querysets and not single objects as provided through the signal handler.

Fix model multiple choice preference to react correctly to deletion handler

---

dynamic_preferences/management/commands/checkpreferences.py
tests/test_checkpreferences_command.py

In some case you might not want to prefill the cache, only to cleanup
the removed preferences. Thus it would be convenient to skip the
creation steps.

Allow to skip preference creation when checkpreferences is invoked

---

docs/installation.rst
dynamic_preferences/apps.py
dynamic_preferences/settings.py
tests/test_global_preferences.py

This is true by default, but when set to false, the
GlobalPreferenceModel isn't registered anymore when ready() is called on
the app config.
This is needed when you want to register your own model in one of your
apps (e.g. a subclass of GlobalPreferenceModel).

Add ENABLE_GLOBAL_MODEL_AUTO_REGISTRATION setting

---

dynamic_preferences/__init__.py

Fix warnings:
```
RemovedInDjango41Warning: 'dynamic_preferences' defines default_app_config = 'dynamic_preferences.apps.DynamicPreferencesConfig'. Django now detects this configuration automatically. You can remove default_app_config.
```

Fix default_app_config deprecation

---

.github/workflows/tests.yml
README.rst
dynamic_preferences/serializers.py
tox.ini

SInce updating to django 4.1, I've starting getting the following warning, which this PR fixes:
```
../usr/local/lib/python3.10/site-packages/dynamic_preferences/serializers.py:17
/usr/local/lib/python3.10/site-packages/dynamic_preferences/serializers.py:17: RemovedInDjango50Warning: The django.utils.timezone.utc alias is deprecated. Please update your code to use datetime.timezone.utc instead.
from django.utils.timezone import (
```
Also I've gone ahead and added python 3.11 to the version list :)

Remove warning in django 4.1 and add support for python 3.11 (#1)

---

dynamic_preferences/serializers.py
tests/test_serializers.py

If you make a PATCH call to a dynprefs endpoint to update a ModelMultipleChoicePreference field, it will not correctly handle the list of PKs. It will transform the value to a list of model instances, which is not handled by the field serializer, as you can see at the issue #291. 
With this patch that list of model instances is transformed to a list of their PKs.
The tests were previously failing so I'm not touching those.

Fix modelmultipleserializer PATCH API call, fixes #291

---

.github/workflows/tests.yml
tox.ini

- Added python 3.11 tests in CI
- Removed unecessary concurrency lock
- Tests under Django 4.2 (remove Django 4.1)
- Tests under Django main / python 3.11

CI Improvements

---

dynamic_preferences/serializers.py
tests/test_types.py

If you have Django 4.2 and latest django-dynamic-preferences==1.15.0 and you try to do something like this:
```
import pickle
from dynamic_preferences.types import  FilePreference
from dynamic_preferences.registries import global_preferences_registry
global_preferences = global_preferences_registry.manager()
@register_preference
class AllCategoryImage(FilePreference):
name = 'all_category_image'
verbose_name = 'Header image for catalog'
item = global_preferences['catalog__all_category_image']
pickled_result = pickle.dumps(item)
```
It will result in the error `AttributeError: Can't pickle local object 'PreferenceFieldFile.__init__.<locals>.FakeInstance'`
It worked well with Django 2.x but in newer Django also `field`  and `instance` attributes are added to `__setstate__` -> …

Added ability to pickle FilePreference in Django 4.2

---

dynamic_preferences/preferences.py

Without the r prefix, it's an invalid escape sequence. It just blowed up in our CI, and I don't know why it did not blow earlier.
```
File "/builds/.venv/lib/python3.10/site-packages/dynamic_preferences/preferences.py", line 25
if not re.match("^\w+$", name):
^^^^^^^
SyntaxError: invalid escape sequence '\w'
```

add raw prefix to invalid regex

---

dynamic_preferences/api/viewsets.py

Calling a bulk update on this api with an empty payload throws an unhandled exception here, error 500.
Handling this error now.

return 400 when calling bulk update with an empty payload

---

docs/quickstart.rst

Otherwise, it does not render properly.

fix(docs): Fix quote in quickstart guide

---

CONTRIBUTING.rst
docs/index.rst

The index page of the docs still mentioned old versions. Depending on your search engine, this is the first page you encounter.

fix(docs): Update Python and django versions in docs

---

dynamic_preferences/forms.py
dynamic_preferences/serializers.py
dynamic_preferences/users/forms.py
requirements.txt
setup.py

Project states it only support Python 3, so these Python 2 crumbs can be cleansed
https://wiki.debian.org/Python3-six-removal

remove six usage

---

dynamic_preferences/serializers.py

Fix #226 
I believe this solves the problem when a pk is not of type int, for example when models have pk of type uuid.

Fix conversion of non-integer pk value in ModelSerializer

---

docs/react_to_updates.rst
dynamic_preferences/api/serializers.py
dynamic_preferences/managers.py
tests/test_preferences.py
tests/test_rest_framework.py

Changes have been made to the `update` method of the PreferenceSerializer to trigger the `preference_updated` signal.
It has been tested for single updates and bulk updates.
I have also added the preference instance to the signal's parameters as it may be needed when you want to retrieve the model bound to a preference, like a workspace, or a user.

Fix #310 The `preference_updated` signal is now triggered when using the REST API

---

.github/workflows/tests.yml
requirements-test.txt
setup.py
tox.ini

No tests broke with the new versions of Python/django, but it's still good to ensure the tests run in CI ;)

Drop support for python 3.8, django 3.2, run tests on python 3.12, 3.13 and django 5.1
