agateblue/django-dynamic-preferences

- dynamic_preferences/registries.py
https://github.com/EliotBerriot/django-dynamic-preferences/issues/3
> Added try/catch to aid pip install

- .travis.yml
- tox.ini
Example: https://travis-ci.org/Crystalnix/django-dynamic-preferences/builds/92675038
> Improvements for travis-ci #22

- .gitignore
- dynamic_preferences/admin.py
> made name, section read-only in django admin

- dynamic_preferences/serializers.py
- dynamic_preferences/types.py
- tests/tests.py
With apologies if I got the tests wrong — I'm a bit rusty on that front
> Working on #12: adding FloatPreference

- dynamic_preferences/managers.py
- tests/tests.py
Fix PreferenceManager.get() when cache is disabled.
> Fix issue #57

- dynamic_preferences/urls.py
- runtests.py
- tests/settings.py
- tests/urls.py
Add compatibility with Django 1.10
> Feature/django 1.10

- AUTHORS.rst
- HISTORY.rst
- dynamic_preferences/__init__.py
- setup.py
> Version bump and changelog

- dynamic_preferences/serializers.py
- dynamic_preferences/types.py
- tests/test_app/dynamic_preferences_registry.py
- tests/test_global_preferences.py
- tests/test_serializers.py
- tests/test_types.py
@EliotBerriot based on our discussion in #8 I've added `DurationPreference` first as I might be needing this. Implementation was straightforward as I expected.
Could you take a look into it and see if it makes sense?
> Add duration preference type

- dynamic_preferences/serializers.py
- dynamic_preferences/types.py
- tests/test_app/dynamic_preferences_registry.py
- tests/test_global_preferences.py
- tests/test_serializers.py
- tests/test_types.py
For #8 
@EliotBerriot I've pushed a PR for `DatePreference first` for you to take a look. I initially wanted to do `DateTimePreference` as well but then I realised it is slightly more tricky due to timezone. Since Date is relatively straightforward I thought this can be reviewed and merged first.
For `DateTime` I'll send another PR explaining how I've implemented it.
> Add date preference

- dynamic_preferences/api/viewsets.py
- tests/test_user_preferences.py
> Failing test case for #103

- dynamic_preferences/admin.py
- dynamic_preferences/preferences.py
- tests/test_app/dynamic_preferences_registry.py
- tests/test_global_preferences.py
Added verbose_name of section to admin so it is more readable for users.
Also added filter with verbose name.
> Section verbose name

- docs/bind_preferences_to_models.rst
Section comes from dynamic_preferences.preferences, not from dynamic_preferences.types
> fix wrong import statement

- dynamic_preferences/serializers.py
> Add missing `format()` to IntegerSerializer exception text

- dynamic_preferences/admin.py
Title pretty much says it all...
> Show the default value in the Django Admin

- dynamic_preferences/serializers.py
- dynamic_preferences/types.py
- tests/test_serializers.py
A feature of issue #143 
Also fixes issue #144
> ModelMultipleChoicePreference

- docs/rest_api.rst
- dynamic_preferences/api/viewsets.py
- tests/test_rest_framework.py
> add section filter in query string for DRF list endpoint

- dynamic_preferences/users/registries.py
Fix UserPreferenceFormView following GlobalPreferenceForm example
> Fix UserPreferenceRegistry and its 'section_url_namespace' attribute

- dynamic_preferences/migrations/0005_auto_20181120_0848.py
Fixes #160. No tests were added since this is only adding migrations file.
> Run makemigrations to add missing migrations file

- HISTORY.rst
- docs/index.rst
- docs/react_to_updates.rst
- dynamic_preferences/managers.py
- dynamic_preferences/signals.py
- tests/test_preferences.py
- tox.ini
> Emit signal on preference update

- dynamic_preferences/managers.py
These fixes have been lying around uncommited here.
Sorry for the noise (but I figure you didn't test before merging either, heh ;)?)
> Fix mistakes in sending preference_updated signal

- dynamic_preferences/registries.py
Also, a PyPI upload would be most appreciated.
> Fix import of FieldDoesNotExist

- docs/quickstart.rst
User forms were moved to a separate app awhile back
> Update forms docs

- docs/lifecycle.rst
- docs/rest_api.rst
- docs/upgrade.rst
- dynamic_preferences/api/viewsets.py
- dynamic_preferences/registries.py
Fix the typos in the comments and documents.
> Fix the typos in the comments and documents

- docs/rest_api.rst
My first commit. Very nice. Can I now claim the OSS developer badge?
> Fixed a typo in documentation

- dynamic_preferences/serializers.py
- tests/test_serializers.py
> FloatPreference can be initialized with either int or float

- docs/installation.rst
- dynamic_preferences/managers.py
- dynamic_preferences/settings.py
> Added config option to specify the cache to use

- .github/workflows/tests.yml
- dynamic_preferences/__init__.py
Unfortunately, had to revert https://github.com/agateblue/django-dynamic-preferences/pull/262 because this breaks in build
> Fix broken builds

- dynamic_preferences/apps.py
- dynamic_preferences/users/apps.py
Fixes https://github.com/agateblue/django-dynamic-preferences/issues/276
> Add autofield to apps

- dynamic_preferences/admin.py
- example/example/apps.py
- example/example/settings.py
- example/example/urls.py
> Fix #281: ensure preference_updated signal is trigerred when updating preference through admin UI

- dynamic_preferences/managers.py
The `load_from_db` method currently calls `to_cache` individually for each entry not already present in the cache. This MR optimizes the existing feature by using the [`set_many`](https://docs.djangoproject.com/en/dev/topics/cache/#django.core.caches.cache.set_many) cache method to perform a batch update.
The performance impact really depends on the cache backend being used: for instance for `LocMemCache`, there is no impact at all, because `set_many` is [just the `set` method being called within a `for` loop](https://github.com/django/django/blob/main/django/core/cache/backends/base.py#L301). However for other types of backends like [Redis](https://github.com/django/django/blob/main/django/core/cache/backends/redis.py#LL138C5-L138C17) or …
> Optimize cache update by batch
